name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Demo LS on VPS
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd public_html/
            git clone git@github.com:volkoffff/symfony_s5.git
            cd wr506
            git pull
            composer install
            php bin/console doctrine:database:create
            php bin/console c:c